// E:\donation_click\phrases.js

const successMessages = [
    "UAU! Você conseguiu! Que pontaria!",
    "NA MOSCA! Sua mira é lendária! Agora só falta o PIX.",
    "ACERTOU! Parabéns! Você é demais! Pode preparar o real.",
    "Mandou bem! A bola não teve chance. Hora de exercer seu privilégio de doar!",
    "Você é incrível! Acertou em cheio! Meu R$1 imaginário já sorri.",
    "Missão cumprida! O botão vermelho foi conquistado. A doação é o próximo nível!",
    "Que precisão cirúrgica! O R$1 está mais perto do que nunca.",
    "Você tem olhos de águia e dedos de ouro! Doar é seu destino.",
    "Impressionante! A bola se curvou à sua vontade. E meu bolso também, com R$1.",
    "GG WP! (Good Game, Well Played). Agora o 'P' também pode ser de PIX!",
    "Sensacional! Você e essa bola têm uma conexão. Uma conexão de R$1.",
    "Objetivo alcançado! O som do clique certeiro ecoa como o tilintar de uma moeda.",
    "Você não erra, você dá aula! Aula de como me doar R$1.",
    "Estou começando a achar que você treinou para isso. Ou só quer muito me doar R$1.",
    "A cada acerto, um programador fica feliz. E potencialmente R$1 mais rico (em espírito).",
    "Você é o Pelé dos cliques! O Messi do mouse! O R$1 é seu para dar!",
    "Conseguiu de novo? Já pode pedir música no Fantástico da Doação.",
    "Se cliques fossem ouro, você já teria uma mina. Mas aceito R$1 em PIX mesmo.",
    "Absolutamente brilhante! Sua generosidade em doar R$1 será lembrada.",
    "Fenomenal! A bola tremeu na base antes do seu clique vitorioso.",
    "Direto ao ponto! Ou melhor, à bola! E agora, direto à doação!",
    "Você tem o toque de Midas... só que em vez de ouro, você me dá o direito a R$1.",
    "Perfeito! Como um poema, mas em forma de clique e com potencial de doação.",
    "Sua habilidade é indiscutível. Assim como seu direito de me doar.",
    "Eu sabia! Tinha um pressentimento que você conseguiria... me dar a chance de pedir R$1.",
    "Sem palavras! Apenas... obrigado pela oportunidade de receber sua doação.",
    "Você é um mestre! A bola é sua tela, e o clique, sua obra-prima doadora.",
    "Fantástico! Você elevou o ato de clicar a uma forma de arte... e de caridade.",
    "Excepcional! Se houvesse um ranking, você estaria no topo... dos meus doadores em potencial.",
    "Bravo! Bravíssimo! O show de cliques merece um R$1 de aplauso.",
    // Novas frases de sucesso:
    "IMPECÁVEL! Sua precisão é uma obra de arte. O R$1 é a moldura!",
    "ALVO ATINGIDO! Próxima parada: minha conta bancária. Brincadeira... ou não!",
    "VOCÊ CONSEGUIU! A lenda do clique certeiro se confirma! Pode mandar o PIX da vitória.",
    "QUE JOGADA! A bola nem viu o que a atingiu. Meu R$1 também não verá... até chegar!",
    "EXCELSIOR! Você ascendeu ao panteão dos doadores em potencial!",
    "OLHA ELE(A) AÍ! O mestre dos cliques ataca novamente! O R$1 imaginário agradece.",
    "PERFEIÇÃO! Se houvesse um placar, você teria quebrado o recorde... de me deixar feliz por R$1.",
    "FEITO! Mais um clique, mais uma chance de ouro (ou de PIX)!",
    "É ISSO AÍ! Habilidade desbloqueada: Doar R$1 com Estilo.",
    "Sua mira é tão boa que deveria vir com manual. Manual de como fazer PIX.",
    "PONTO PARA VOCÊ! E um real para mim, quem sabe?",
    "A bola se rendeu! Agora só falta você se render à generosidade do PIX.",
    "NÍVEL MÁXIMO DE MIRA! O R$1 é seu... para me dar, claro.",
    "SUCESSO TOTAL! Você e o botão de doar: um caso de amor prestes a acontecer.",
    "ACERTO CRÍTICO! Dano de R$1 aplicado... na minha lista de desejos.",
    "Mágico! Fez a bola sumir... no seu clique! Agora faça R$1 aparecer na minha conta.",
    "MVP! MVP! MVP! Most Valuable Player... e potencial doador!",
    "Você não brinca em serviço! E eu não brinco quando digo que aceito PIX.",
    "BRILHANTE! Acendeu a chama da esperança... e do meu QR Code.",
    "TIRO CERTO! Direto no alvo, e quem sabe, direto na minha carteira digital.",
    "Que performance! Digno de aplausos e de uma contribuição simbólica de R$1.",
    "Você zerou o jogo do clique! Próximo chefão: o app do banco.",
    "Sem defeitos! Sua técnica é apurada. E meu PIX também está pronto.",
    "A precisão de um ninja, a generosidade de um... bom, de você, eu espero!",
    "CONQUISTA DESBLOQUEADA: 'O Doador Lendário (em Potencial)'.",
    "Estou vendo um futuro brilhante para nós... e R$1 nele.",
    "Isso foi tão bom que até a bola ficou sem palavras. Eu fico sem R$1 se você não doar.",
    "Você é um sniper do mouse! O alvo? A glória... e meu PIX.",
    "Cada clique certo é um passo a mais na jornada do R$1.",
    "Dominou! A arena de cliques é sua. A doação também pode ser.",
    "Show de bola! Literalmente. Agora, show de PIX?",
    "Incendiou o parquinho! Ou melhor, a área de jogo. O R$1 tá quase queimando no seu bolso.",
    "Você é tipo o Rei Arthur da Távola Redonda... só que com cliques e uma bola vermelha. Cadê o Graal de R$1?",
    "Se cliques pagassem minhas contas, você seria meu benfeitor. Mas como não pagam, aceito R$1.",
    "Essa foi na veia! Ou melhor, na bola. O R$1 tá na agulha?",
    "Matou a pau! A bola, claro. Agora, ressuscite minha esperança com R$1.",
    "Sua mira é mais certeira que horóscopo de segunda-feira. E mais lucrativa (pra mim, espero).",
    "Você não está para brincadeira! E meu R$1 imaginário também não está... quer virar real.",
    "Que tiro foi esse?! Certeiro! O R$1 pode ser o próximo.",
    "Você está on fire! Cuidado pra não queimar a ponta do dedo... ou a chance de doar."
];

const failMessagesSarcastic = [
    "Infelizmente, você não é capaz de me doar R$1. Que pena...",
    "Cara, você não consegue acertar isso? A bola estava praticamente parada!",
    "Errrrou! Parece que meu R$1 está seguro... por enquanto.",
    "Talvez mirar não seja seu forte. Que tal tentar... palavras cruzadas?",
    "A bola estava BEM ALI! Mais sorte na próxima (ou não).",
    "Quase! Mas 'quase' não clica na bola. E 'quase' não me doa R$1.",
    "A bola riu da sua tentativa. Eu também, mas por dentro.",
    "Você está chegando perto... de me fazer desistir de esperar esse R$1.",
    "Foi por pouco! Só que 'pouco' é a distância entre você e a bola.",
    "Mirou na bola e acertou na minha paciência. Brincadeira... ou não.",
    "Será que o mouse está com defeito? Ou seria o operador?",
    "Até minha avó acertaria essa... se ela jogasse. E talvez até sem óculos.",
    "A bola continua intacta. E meu saldo também. Que alívio para ela!",
    "Respira fundo. Concentra. E... erra de novo, quem sabe?",
    "Não se preocupe, a bola não guarda rancor. Eu, talvez um pouquinho, pelo R$1 que não veio.",
    "Você tem certeza que não é melhor tentar um jogo de tabuleiro?",
    "A força foi, mas a mira ficou. E meu R$1 também.",
    "O desvio padrão do seu clique foi... considerável.",
    "Isso foi um clique ou um suspiro de frustração perto do mouse?",
    "Continue tentando! Uma hora você acerta. Ou cansa.",
    "A bola se sente vitoriosa. E eu, R$1 menos potencialmente rico.",
    "Será que estamos participando de esportes olímpicos de 'quase acerto'?",
    "Se errar fosse um superpoder, você seria o Superman dos cliques.",
    "Não foi dessa vez. Nem da anterior. Mas quem sabe da próxima?",
    "A bola agradece por não ter sido esmagada. Eu agradeceria pelo R$1.",
    "O vento deve ter desviado seu mouse. Só pode.",
    "Habilidade em falta. Doação em espera eterna.",
    "Eu já estava com o app do banco aberto aqui... que dó.",
    "Talvez se você pedir com jeitinho, a bola se move para o seu cursor?",
    "Pense pelo lado positivo: você está ficando bom em errar com estilo.",
    // Novas frases de falha sarcástica:
    "A bola está rindo em vermelho. E eu também, mas de nervoso.",
    "Talvez precise de um mouse maior? Ou uma bola maior? Ou mais R$1 de incentivo?",
    "Quase... tão perto quanto o Brasil do hexa em algumas Copas. Ou seja, nem tanto.",
    "O mouse escorregou? Ou foi a sua vontade de me doar R$1 que sumiu?",
    "Seus cliques estão em modo 'economia de energia'? A bola agradece.",
    "Acho que a bola desenvolveu um campo de força anti-clique... só para você.",
    "Não foi falta de tentativa, foi... falta de mira mesmo. Meu R$1 continua sonhando.",
    "Até um peixe fora d'água teria mais chance. Pelo menos ele se debate perto.",
    "A bola está segura. Meu R$1 também. Suspeito que haja uma conexão.",
    "Você está testando os limites da minha paciência... e da área de jogo.",
    "Isso foi um clique ou um pedido de desculpas à bola por errar tanto?",
    "Se errar fosse um esporte olímpico, você já teria patrocínio. E eu, R$0.",
    "A bola parece estar se divertindo mais que você. E certamente mais que meu bolso.",
    "Não desanime! Algum dia... talvez... quem sabe... você acerta. Ou doa por pena.",
    "Alguém chamou o VAR? Porque essa mira foi claramente... para fora.",
    "O R$1 imaginário está começando a perder a fé. E eu, a esperança.",
    "A bola criou um fã-clube. Você não está nele. Nem meu R$1.",
    "Essa foi por tão pouco que o 'pouco' se sentiu ofendido.",
    "Acho que o problema não é o mouse, nem a bola. É o R$1 que não quer vir.",
    "Tem certeza que a tela está ligada? E o mouse conectado?",
    "A bola está pensando em se aposentar invicta contra seus cliques.",
    "Não se preocupe, a prática leva à perfeição. Ou à desistência. Meu R$1 espera ansiosamente.",
    "Seus reflexos são de um... bicho-preguiça tentando pegar uma mosca velocista.",
    "O vento deve estar forte aí dentro. Só pode ser isso.",
    "A bola agradece pela massagem de ar que seu clique proporcionou ao redor dela.",
    "Estou começando a achar que você está fazendo isso de propósito só para não doar.",
    "Que mira abstrata! A bola ficou confusa. E eu, sem R$1.",
    "Se existisse um prêmio de 'quase lá', você seria campeão invicto.",
    "A força gravitacional da Terra parece estar desviando seus cliques da bola.",
    "Meu R$1 está seguro e quentinho, longe dos seus cliques. Que alívio... para ele.",
    "A bola mandou um 'joinha' sarcástico pela sua tentativa.",
    "Seu mouse tem vida própria e um péssimo senso de direção?",
    "Errar é humano. Persistir no erro é... bem, é o que você está fazendo. E eu continuo sem R$1.",
    "A bola está começando a achar que você tem algo pessoal contra ela.",
    "Faltou o 'Q' de 'Quase Acertei'... e o 'R' de 'Real na minha conta'.",
    "Talvez umas aulas de 'clique ao alvo'? Ou um tutorial de PIX?",
    "A bola está criando raízes de tanto ficar parada esperando seu clique certeiro.",
    "Seu nível de 'quase' está impressionante hoje. Meu R$1 que o diga.",
    "Acho que vou colocar um GPS na bola pra te ajudar. E um QR Code do PIX nela também.",
    "Essa doeu... na minha esperança de ganhar R$1.",
    // Novas frases de falha sarcástica:
    "A precisão está mais para Wi-Fi em dia de chuva.",
    "Você clicou? Ou só pensou bem forte em clicar?",
    "Isso foi um protesto silencioso contra a doação?",
    "Nem se a bola tivesse o dobro do tamanho você acertava.",
    "A bola estava tão sozinha... até seu clique errar o endereço.",
    "Essa mira tá com GPS desligado, né?",
    "O universo conspirou... contra sua precisão.",
    "Já tentou fechar os olhos? Pode ser que melhore.",
    "A bola até piscou esperando, mas você não colaborou.",
    "Seus cliques têm alma livre. Nunca querem acertar.",
    "Quase acertou... o botão de fechar o jogo.",
    "Com essa mira, nem sniper de Star Wars perderia pra você.",
    "A bola mandou um áudio: 'kkkkkkk, sério isso?'",
    "Já pensou em virar poeta? Porque de sniper você não tem nada.",
    "Seu clique foi tipo promessa de político: quase fez algo.",
    "Esse clique foi tão fora que eu achei que era lag.",
    "Você tentou. E falhou. Mas pelo menos tentou.",
    "Se fosse pra errar com estilo, você teria um Oscar.",
    "A bola até deu uma risadinha. Eu ouvi.",
    "Você já pensou em fazer stand-up? Porque esse clique foi uma piada.",
    "Parece que você está jogando com o pé.",
    "A bola ficou até constrangida de tão longe que passou.",
    "Você já ouviu falar em coordenação motora? Pois é.",
    "A chance passou voando. Você passou... assistindo.",
    "Isso foi um teste? Porque parece que você não estava tentando de verdade.",
    "Se a bola tivesse um escudo, nem precisava usar.",
    "A mira tá calibrada pra Marte?",
    "Parabéns, você conseguiu errar algo que nem se mexe.",
    "Essa bola poderia estar em outro continente e ainda seria errada por você.",
    "O mouse piscou. Achou que era erro de fábrica.",
    "A precisão foi igual a minha vontade de trabalhar: inexistente.",
    "Sabe o que é pior que errar? Errar de novo.",
    "Você desbloqueou o modo: 'erro constante'.",
    "Meu R$1 ficou até tranquilo com essa tentativa.",
    "Esse clique foi tão perdido que eu vou mandar procurar no Google Maps.",
    "Se fosse pra evitar o alvo, você seria um gênio.",
    "A bola abriu um processo por negligência.",
    "Com essa mira, você tá mais pra estilingue quebrado.",
    "Errou com convicção, pelo menos.",
    "O jogo vai mudar de nome pra 'Desviar da Bola'.",
    "Você joga no modo difícil: com os olhos fechados.",
    "A bola ficou intacta. Seu ego, nem tanto.",
    "Esse clique foi tipo Wi-Fi ruim: cheio de esperança, zero resultado.",
    "A bola suspirou. Não de medo, de tédio.",
    "Já pensou em doar R$1 só pra compensar o vexame?",
    "Você está cada vez mais perto... de fechar o jogo.",
    "De todos os lugares pra clicar, você escolheu o errado.",
    "Se errar fosse arte, você era um Picasso do fracasso.",
    "Esse mouse tá com delay... de 5 anos.",
    "Alvo? Que alvo?",
    "Um pouco mais pro lado e você acertava... o menu do navegador.",
    "A bola pensou: 'ah não, de novo não'.",
    "Seus cliques têm vontade própria. E elas não gostam da bola.",
    "A cada erro, um R$1 sobrevive.",
    "Você é o herói da resistência... à doação.",
    "Clique errado. Mas pelo menos foi com estilo.",
    "A bola não foi atingida. Mas seu orgulho sim.",
    "Sua mira é tipo Wi-Fi de shopping: existe, mas não funciona.",
    "Parece que você joga com o cotovelo.",
    "Essa bola já virou patrimônio intocável.",
    "Errou mais uma? Vai tentando, uma hora o universo cansa de te sabotar.",
    "Esse clique foi tipo música ruim: insistente e decepcionante.",
    "Você acabou de bater o recorde de: 'não foi dessa vez'.",
    "Sua mira foi aprovada... por engano.",
    "Tem certeza que você não está testando a paciência da bola?",
    "Você é tipo o Neo da Matrix... se ele errasse todos os tiros.",
    "Errar é humano, mas repetir esse erro é quase arte performática.",
    "Esse erro foi tão bonito que merecia um quadro.",
    "Pelo menos seu clique limpou a tela... de dignidade.",
    "Se a bola tivesse sentimentos, ela estaria rindo até agora.",
    "A mira tá jogando contra você? Troca de time.",
    "Esse clique foi uma homenagem ao vazio.",
    "A precisão está no modo férias.",
    "A bola ficou emocionada com a sua falta de mira.",
    "Já pensou em doar por dó mesmo?",
    "Esse clique foi igual final de novela ruim: ninguém entendeu.",
    "A mira saiu pra comprar pão e não voltou.",
    "Você já pensou que o mouse pode estar te trollando?",
    "Pior que errar é continuar achando que vai acertar assim.",
    "Seu clique é tipo reality show: cheio de drama, pouca ação.",
    "A bola está mandando uma intimação: 'pare de me ignorar'.",
    "A precisão está no modo 'economia extrema'.",
    "Se esse clique fosse um filme, seria de terror.",
    "A bola tá achando que é imune a você.",
    "Se o objetivo fosse errar com confiança, você ganhou.",
    "Já tentei ajudar mentalmente, mas você não colabora.",
    "A mira foi morar com os ETs. Tá em outra galáxia.",
    "O clique foi direto pro limbo dos erros esquecidos.",
    "A bola está criando um blog sobre seus erros.",
    "Você tem talento. Pra drama, não pra acertar.",
    "Errar virou parte da sua personalidade, né?",
    "Esse clique foi patrocinado por 'não hoje'.",
    "Você é o Messi... dos erros.",
    "A bola continua impávida. E você, abatido.",
    "Clique errado, mas com convicção!",
    "A mira tentou, mas você atrapalhou.",
    "Se fosse competição de erros, você já tinha troféu.",
    "Esse erro doeu... no meu desejo de ver R$1.",
    "Se tivesse VAR, ia confirmar: erro claro.",
    "De todas as direções, você escolheu a mais errada.",
    "A bola está tão acostumada que nem se assusta mais.",
    "Errou de novo? Pelo menos você é consistente.",
    "Mais uma tentativa. Mais um erro. Mais uma risada da bola.",
    // Mas frases adicionadas
    "Você atirou na esperança... e errou também.",
    "Já pensou em tentar com a testa? Vai que muda.",
    "Se a bola fosse invisível, ainda não faria diferença.",
    "A bola já te considera parte da decoração.",
    "O clique foi tão ruim que até o JavaScript travou.",
    "Com essa mira, você não acerta nem comentário em post.",
    "A bola abriu um grupo no WhatsApp: 'intocáveis'.",
    "Você tem potencial… para ser lenda urbana do erro.",
    "Errou tão bonito que virou coreografia.",
    "De tão longe que passou, virou satélite.",
    "A bola tá tranquila, nem sentiu a brisa do seu clique.",
    "Clicou onde? No vazio da existência?",
    "Talvez o mouse esteja te sabotando por vergonha.",
    "Esse clique foi tipo dieta na segunda: pura intenção.",
    "Pelo menos a bola se sente valorizada: ninguém toca nela.",
    "Se tivesse que errar de novo, você faria igual.",
    "Seu clique está com delay emocional.",
    "Errar tudo é um dom. E você é abençoado.",
    "Parece que você joga com uma colher.",
    "A bola está mais segura que cofre de banco.",
    "Seu mouse precisa de óculos.",
    "Clicou com a alma, mas ela também errou.",
    "Você tá jogando ou desenhando arte abstrata com o cursor?",
    "A bola nem te considera uma ameaça mais.",
    "Na dúvida, erra de novo.",
    "A precisão tá jogando com outro jogador.",
    "Errou tão longe que abriu um buraco no universo.",
    "Você clicou com raiva e sem rumo.",
    "Se seu objetivo era errar de novo, parabéns.",
    "O mouse pediu demissão por justa causa.",
    "Essa bola já tá com saudade de ser clicada.",
    "Com esse clique você só acertou minha paciência.",
    "A bola piscou e você... errou a piscada também.",
    "Tente de novo. Ou não. O resultado vai ser o mesmo.",
    "Você é a resistência ao acerto.",
    "Acertar é um conceito distante, né?",
    "A bola sentiu um arrepio... de vergonha alheia.",
    "Essa mira é patrocinada por cegueira seletiva.",
    "Você clicou com a força do... nada.",
    "O jogo tá te observando e julgando.",
    "Você tá testando o mouse ou minha paciência?",
    "Cliquei com o coração – e ele tava na esquerda.",
    "A bola até agradece pelo espaço pessoal respeitado.",
    "Isso foi um golpe de misericórdia no acerto.",
    "Clicou com medo? Pareceu.",
    "O botão esquerdo está sofrendo abuso psicológico.",
    "O mouse chorou em silêncio.",
    "A bola tá abrindo um boletim de ocorrência.",
    "A mira foi pra balada e te deixou aqui sozinho.",
    "Se o clique fosse uma aposta, você tava falido.",
    "O cursor foi pra um lado, o juízo pro outro.",
    "Você só acerta o botão de fechar o jogo.",
    "A cada erro, um programador chora.",
    "O universo conspirou contra sua mira. De novo.",
    "A bola está considerando mudar de jogo.",
    "Mais uma chance desperdiçada com elegância.",
    "Sua mira é tipo nuvem: passa, mas nunca acerta.",
    "Errar com frequência já virou rotina, né?",
    "Você é tipo GPS ruim: te leva sempre pro lugar errado.",
    "A bola começou a escrever um livro: '1000 cliques e nenhum acerto'.",
    "Já tentou desligar e ligar você mesmo?",
    "Se existisse um prêmio por desvio, você ganhava.",
    "Você é o mestre do quase.",
    "A bola pensou em mudar de cor. Vai que ajuda.",
    "Tem um ímã no cursor repelindo o acerto?",
    "Você errou com tanta calma que foi quase zen.",
    "Nem se a bola gritasse 'aqui!' você acertava.",
    "O clique viajou no tempo e não voltou certo.",
    "Sua pontaria foi morar com os dinossauros.",
    "Essa bola é sua nêmesis declarada.",
    "A cada erro, um pixel chora.",
    "Você tem talento pra tudo. Menos pra isso.",
    "Clicou com o pensamento. Pena que foi pensamento errado.",
    "A bola já aprendeu a meditar esperando você acertar.",
    "Já pensou em usar o teclado? Vai que dá sorte.",
    "Você é a prova de que errar é humano. E repetitivo.",
    "A precisão foi sequestrada pelo destino.",
    "Você tentou atingir a bola com... boa vontade.",
    "Essa bola já é quase um NFT: intocável e valiosa.",
    "O jogo ficou triste por você.",
    "Esse clique foi quase arte moderna.",
    "A bola pediu licença pra rir.",
    "Clicou no vácuo com precisão cirúrgica.",
    "Se tivesse um prêmio de 'quase', você teria coleção.",
    "A cada clique errado, nasce um novo meme.",
    "A bola tá pensando em mudar de nome pra 'Impossível'.",
    "Se você fosse sniper, o mundo estava a salvo.",
    "O clique foi tão fora que deu erro 404.",
    "Essa mira é alimentada por sonhos frustrados.",
    "Você acertou... o ponto de desistir.",
    "Já tentou jogar com os pés? Pode ser upgrade.",
    "O erro foi tão constante que virou hábito.",
    "A bola já virou lenda urbana do 'intocável'.",
    "Clicou como se estivesse pedindo desculpa.",
    "A precisão fugiu e levou sua autoestima junto.",
    "Esse clique foi um abraço no fracasso.",
    "A bola olhou e disse: 'sério, de novo?'",
    "Sua mira é igual o Saci: desequilibrada.",
    "Clicou no nada e fez o nada se sentir útil.",
    "A bola virou coach de autoestima depois de tantos erros.",
    "Cada clique é um poema de decepção.",
    "Sua mira deveria ser estudada pela ciência.",
    "Até o cursor se perdeu com esse erro.",
    "Se sua mira fosse app, teria 1 estrela na loja.",
    "A bola tá te evitando ou você que não ajuda?",
    "Clicou com tanto entusiasmo que errou em dobro.",
    "A bola abriu um LinkedIn: 'Experiência: nunca tocada'.",
    "A mira decidiu entrar em greve silenciosa.",
    "Esse clique foi um clássico da incompetência moderna.",
    // Mais frases
    "Você errou com tanta classe que pareceu intencional.",
    "A bola tá pensando em colocar uma faixa: 'Proibido acertar'.",
    "Se sua mira fosse um aplicativo, já teria sido desinstalada.",
    "A bola ficou entediada esperando ser clicada.",
    "Se errar desse XP, você já teria zerado o jogo.",
    "Sua mira é igual GPS bugado: recalculando sempre.",
    "Clicou com fé. Faltou o resto.",
    "A bola pediu demissão do jogo. Não aguenta mais ser ignorada.",
    "Você clicou tão mal que o jogo pensou que era bug.",
    "Esse clique foi o equivalente digital de tropeçar no ar.",
    "Sua mira tá mais quebrada que promessa de político.",
    "Você é o MVP da frustração.",
    "Se existisse campeonato de erro, você já teria troféu.",
    "Esse erro fez a bola repensar sua existência.",
    "Você clicou onde a esperança vai pra morrer.",
    "A bola já está cogitando chamar reforços espirituais.",
    "Sua mira tirou férias permanentes.",
    "Você errou com a confiança de quem sabe que vai errar.",
    "Essa tentativa foi tipo relacionamento: começou bem e terminou no desastre.",
    "A bola tá começando a te ignorar por escolha.",
    "Esse clique teve menos direção que conversa de elevador.",
    "Você mirou com o olho fechado e a alma distraída.",
    "Errou com maestria. É um talento raro.",
    "Seu clique foi uma carta de amor... rejeitada.",
    "A bola sorriu. Ironicamente, claro.",
    "Você ativou o modo espectador sem querer.",
    "O mouse tá fazendo greve após esse erro.",
    "A bola está em modo avião pra fugir de você.",
    "Esse erro entrou pro top 10 da história do jogo.",
    "Você acertou em cheio o nada absoluto.",
    "A precisão se recusou a participar dessa tentativa.",
    "Você é um artista performático do fracasso.",
    "A bola vai te bloquear se continuar assim.",
    "Se o jogo fosse sobre errar, você estaria ganhando.",
    "Seu erro é tão consistente que assusta.",
    "A bola está em choque. Nunca viu alguém errar tanto.",
    "Você clicou? Porque o jogo não percebeu.",
    "Sua mira foi abduzida.",
    "Essa tentativa foi mais vazia que geladeira de estudante.",
    "A bola pensou: 'Nem vou reagir'.",
    "Você clicou com o espírito de um golfinho vendado.",
    "Esse clique foi tipo final de novela ruim: decepcionante.",
    "Você tá treinando pra perder ou é natural?",
    "A bola vai abrir um boletim de ocorrência por abandono.",
    "Se você fosse um sniper, o mundo estaria seguro.",
    "Sua mira é tipo Wi-Fi público: nunca funciona.",
    "Errar virou sua zona de conforto.",
    "A bola tá pensando em se camuflar. Nem precisa.",
    "O clique foi tão distante que virou viagem astral.",
    "Você e a precisão estão em cidades diferentes.",
    "A bola pensou que você estava brincando. Ainda pensa.",
    "Você errou e ainda causou efeito borboleta... negativo.",
    "A mira não foi convidada pra essa partida.",
    "Sua pontaria é uma arte pós-moderna: ninguém entende.",
    "O mouse está decepcionado, e com razão.",
    "A bola vai te cobrar aluguel por morar tão longe dela.",
    "Você está desafiando as leis da física... e da lógica.",
    "Esse clique foi a personificação do 'tanto faz'.",
    "Você tá jogando com a mão ou com a esperança?",
    "A bola ficou imóvel. Você também, emocionalmente.",
    "Você conseguiu errar com estilo. Um estilo trágico.",
    "A mira tirou um cochilo no momento decisivo.",
    "Essa bola é o chefe final da sua autoestima.",
    "Você está no caminho... errado, mas tá indo.",
    "Errou como se tivesse um plano. Plot twist: não tinha.",
    "A bola riu. Um riso triste.",
    "Você clicou com a precisão de um polvo entediado.",
    "Esse clique foi uma poesia triste sobre fracassos.",
    "A bola só quer ser amada. Não é pedir demais.",
    "Sua mira foi criada com base num horóscopo genérico.",
    "Se você jogasse dardos, seria banido por segurança.",
    "Essa tentativa foi um protesto silencioso contra o acerto.",
    "Sua mão tremeu de vergonha própria.",
    "O clique falhou no vestibular da precisão.",
    "Você tá tentando ou só explorando o espaço ao redor da bola?",
    "A bola tem mais paz do que monge em retiro.",
    "Você clicou e criou um novo conceito: anticlímax.",
    "Essa bola agora responde por 'a intocável'.",
    "Sua mira é mais indecisa que fila de self-service.",
    "Você é um poeta da imprecisão.",
    "A bola está começando a questionar se você existe.",
    "Esse clique deu a volta no mapa e ainda errou.",
    "Sua mira é um elogio à aleatoriedade.",
    "Você errou com elegância. Trágica, mas elegante.",
    "O mouse te ama, mas está cansado.",
    "Se fosse pra errar sempre assim, eu nem codava o botão.",
    "A bola se inscreveu no ProUni. Quer mudar de vida.",
    "Você é o motivo pelo qual estatísticas existem.",
    "Sua mira bateu recorde: de distância do alvo.",
    "Você clicou na dúvida e errou na certeza.",
    "Essa tentativa foi a tempestade sem chuva.",
    "Você virou referência: 'igual aquele que nunca acerta'.",
    "Esse erro foi tão limpo que pareceu ensaiado.",
    "A bola não tá mais no jogo. Tá na terapia.",
    "Você criou um novo esporte: fugir do alvo.",
    "Esse clique foi o reflexo do caos interior.",
    "A bola te chama de 'visitante frequente do fracasso'.",
    "Você errou como quem escreve com o cotovelo.",
    "Essa mira tá calibrada com vento e esperança.",
    "Você clicou na vibe errada.",
    "Se errar fosse uma empresa, você seria CEO.",
    "O jogo quer te dar um prêmio: 'Melhor ausência de acerto'.",
    "Você é o mestre supremo do quase.",
    "Essa bola já pediu aposentadoria por falta de uso.",
    "Você fez do erro uma filosofia de vida.",
    "O clique teve alma... mas não teve mira.",
    "Se existisse prêmio por tentativa... você ainda erraria o pódio.",
    // Mais frases adicionadas
    "Esse clique foi tão inútil que entrou em depressão.",
    "A bola virou vegana: não quer mais contato humano.",
    "Você clicou com tanta força emocional que quase chorei.",
    "A mira pediu demissão e foi vender arte na praia.",
    "A bola ficou tão parada quanto sua evolução no jogo.",
    "Você tá praticando o esporte olímpico do erro.",
    "Se fosse corrida, você tropeçava antes da largada.",
    "Esse clique nem o Google consegue explicar.",
    "Sua mira é a maior prova de que o caos existe.",
    "Você errou com tanta confiança que pareceu arrogância.",
    "A bola virou um conceito filosófico: inalcançável.",
    "Clicou como quem joga a culpa nos astros.",
    "Esse erro foi patrocinado por falta de noção.",
    "Você é o 'exemplo do que não fazer' em tutoriais.",
    "A bola já tem saudades do tempo em que ninguém errava.",
    "Sua mira tá usando modo randômico nível avançado.",
    "Você errou com uma elegância que assustou a física.",
    "Esse clique foi tão fora que virou desabafo.",
    "Se o objetivo era errar artisticamente, parabéns.",
    "Sua mira é igual promessa de político: nunca cumpre.",
    "Você conseguiu errar em câmera lenta.",
    "A bola tá organizando um protesto contra seus cliques.",
    "Se a precisão fosse remédio, você ainda estaria na bula.",
    "Você é tipo comercial no YouTube: ninguém quer.",
    "O clique falhou em três dimensões.",
    "Errou tão bem que deveria ensinar como não fazer.",
    "Você e a bola têm um relacionamento tóxico: sem toque.",
    "Esse clique foi igual piada ruim: constrangedor.",
    "A mira fugiu pra um retiro espiritual.",
    "A bola abriu um OnlyFans: só pros que conseguem tocá-la.",
    "Você clicou e ativou o modo 'vergonha pública'.",
    "Esse erro gerou uma crise existencial na bola.",
    "Clicou com a leveza de um dinossauro bêbado.",
    "Se a mira fosse um carro, estaria sem rodas.",
    "Esse erro foi o ponto alto do seu desempenho… infelizmente.",
    "Você errou com tanta fé que virou religião.",
    "A bola se inscreveu em aulas de invisibilidade.",
    "Sua pontaria é igual a previsão do tempo: só acerta sem querer.",
    "Esse clique serviu apenas pra testar minha paciência.",
    "A bola está considerando mudar de planeta.",
    "Se existisse troféu por persistência no erro, já era seu.",
    "Você clicou como se estivesse pedindo desculpas.",
    "A mira foi buscar pão e nunca voltou.",
    "Essa tentativa ativou o modo 'vergonha alheia'.",
    "Você tem a precisão de um pato com labirintite.",
    "A bola tá mais intocável que senha de Wi-Fi vizinho.",
    "Esse erro foi tão épico que entrou pra história oral do jogo.",
    "Você acertou o coração do fracasso.",
    "A mira tá operando via Wi-Fi com sinal fraco.",
    "Você clicou e destruiu a esperança de acerto.",
    "Se fosse pra errar bonito, você seria modelo.",
    "Esse clique foi a definição de 'por que tentar?'.",
    "Sua mira foi detectada como ameaça à dignidade.",
    "Você clicou com a suavidade de um caminhão sem freio.",
    "A bola já te considera um fã distante.",
    "Errou como quem sabe que vai errar.",
    "A mira desligou o monitor só pra não ver.",
    "Esse erro ecoou até no código-fonte.",
    "Clicou no vazio e preencheu de decepção.",
    "Você é o ninja da imprecisão: ninguém te vê acertar.",
    "Esse clique foi um tapa na cara da lógica.",
    "Sua pontaria é um universo paralelo sem acertos.",
    "A bola pensou que você era só decoração do jogo.",
    "Você clicou com a firmeza de um gelatina triste.",
    "Se fosse fácil, ainda assim você errava.",
    "Esse erro foi tão previsível que causou déjà vu.",
    "Você clicou em um ponto... do desespero.",
    "A bola tá pensando em te bloquear.",
    "Se fosse teatro, seria drama cômico.",
    "Sua mira é patrocinada pelo acaso.",
    "Esse clique foi tão inútil que entrou em loop eterno.",
    "Você errou com estilo: estilo 'fracasso'.",
    "A bola já fez amizade com o tédio.",
    "Esse erro foi tão bonito que merecia moldura.",
    "Você clicou como se não estivesse presente.",
    "A precisão foi para um spa. Tá estressada contigo.",
    "Clicou tão mal que o sistema pediu desculpas.",
    "Você atinge o impossível... de errar o óbvio.",
    "Essa bola já virou personagem místico de tão intocada.",
    "O clique foi um hino à desilusão.",
    "Sua mira é uma metáfora sobre a vida: nada faz sentido.",
    "Você é uma lenda urbana: 'aquele que nunca acerta'.",
    "Esse erro foi profundo. Deu até pra refletir.",
    "Você clicou e o universo suspirou… de frustração.",
    "A bola escreveu um diário: 'Mais um dia intocada'.",
    "Sua mira é como Wi-Fi no metrô: falha sempre.",
    "Você tem a pontaria de um polvo sonâmbulo.",
    "Errou com alma, coração e total ausência de direção.",
    "A bola virou conceito: inalcançável e misteriosa.",
    "Esse erro ativou o modo 'piada triste'.",
    "Você clicou com a precisão de um golfinho cego.",
    "A bola agora atende por 'a inalcançável'.",
    "Você mirou na glória e acertou a vergonha.",
    "O clique falhou tanto que ativou a autocrítica.",
    "Você é o Picasso do erro: criativo e incompreendido.",
    "Esse erro foi filosófico: o clique que não foi.",
    "A bola considerou se camuflar. Mas nem precisa.",
    "Você clicou como quem tá tentando desligar a vida.",
    "Esse erro foi tipo final de série ruim: decepcionante.",
    "Você transformou a falha em ritual sagrado.",
    "Sua mira é tipo boato: nunca chega ao destino certo.",
    "Clicou? Foi simbólico então.",
    "A bola entrou no modo 'zen': inatingível e serena.",
    "Você errou de novo, e agora com convicção.",
    "Esse clique foi a versão interativa do fracasso.",
    // Mais frases de pix
     "Errou feio, errou rude... e o PIX também nem sentiu o perigo.",
    "Nem o Fantasma do PIX apareceu dessa vez. Que decepção.",
    "Isso foi um 'anti-Pix': tirou até a vontade de doar.",
    "A bola escapou, e meu sonho de R$1 também.",
    "A sua mira tá igual saldo da conta: zerada.",
    "Seu clique foi tão longe do alvo quanto meu R$1 do seu bolso.",
    "O PIX ficou até constrangido com esse erro.",
    "Se eu ganhasse R$1 por cada erro seu… já teria o que você ainda não me doou.",
    "Nem o estagiário da Receita Federal perdoaria esse erro de doação.",
    "O app do banco fechou sozinho de vergonha.",
    "A bola desviou? Ou foi sua dignidade fugindo do PIX?",
    "Errou! Mas tudo bem, meu QR Code continua chorando.",
    "Você está jogando ou evitando caridade?",
    "PIX cancelado por falta de pontaria.",
    "A bola agradece. Minha carteira não.",
    "Sua mira fez o banco suspender transferências por motivos de inutilidade.",
    "Clique assim só serve pra dar unfollow, não pra doar.",
    "O botão de doar está em greve até você acertar.",
    "Seu clique foi negado pela central de doações.",
    "A bola tá parada, mas sua intenção de doar é que não se move.",
    "Parece que o único movimento aqui é o de me deixar no prejuízo.",
    "Com essa mira, nem QR Code salva.",
    "O Banco Central emitiu alerta: perigo de zero doações à vista.",
    "Até o Itaú já desistiu de esperar o PIX.",
    "Você só erra? Tá em treinamento pra ser antivacina de doação?",
    "Essa tentativa foi tão fraca que o Nubank pediu retratação.",
    "Você tá tentando ou só simulando boa vontade?",
    "O clique foi leve. Sua culpa, ainda mais leve. Meu R$1? Nem sinal.",
    "A bola está estática. Já seu bom senso pra doar parece em movimento... de fuga.",
    "Isso foi tão ruim que o Banco do Brasil fechou a agência mais próxima.",
    "Sua mira é tipo boleto: vem, mas não resolve nada.",
    "Errar faz parte. Mas ignorar o PIX é sacanagem.",
    "A única coisa que chegou perto foi minha esperança... de novo frustrada.",
    "Cadê aquele R$1 prometido nos seus pensamentos?",
    "Doar não dói. Mas errar assim machuca meu coração... e minha conta.",
    "A cada erro seu, meu QR Code se desintegra um pouquinho.",
    "Essa mira tem o selo 'PIX recusado'.",
    "A bola ficou imóvel. Igual seu compromisso com a doação.",
    "Se clique errado doasse, você já teria me aposentado.",
    "O app do banco fechou por inatividade... sua.",
    "Errou! Mas o sistema de cobrança emocional continua ativo.",
    "Esse erro foi patrocinado por: 'Esquiva do PIX'.",
    "Não foi por falta de vontade... foi por falta de R$1.",
    "A bola venceu de novo. Meu Pix perdeu. Parabéns!",
    "Essa tentativa foi como meu extrato: vazia.",
    "Se dependesse do seu acerto, meu almoço era só esperança.",
    "Você é tão bom em errar que o banco cancelou seu Pix pré-aprovado.",
    "Esse clique foi aprovado com ressalvas pela comissão anti-doação.",
    "Até o boleto que vence hoje ficou com pena.",
    "O banco bloqueou esse clique por suspeita de ausência de caridade.",
    "Você ativou o modo 'Esquiva de Doar'. Parabéns!",
    "Com esse nível de erro, até o QR Code entrou em modo avião.",
    "Doar R$1? Só depois de acertar essa bola que parece invisível pra você.",
    "Pix fantasma confirmado. Aparece, mas nunca chega.",
    "Você é um exemplo... de como não fazer uma doação.",
    "Se a intenção conta, a sua nem apareceu no radar.",
    "Erro confirmado! O R$1 voltou pra base.",
    "PIX? Só se for o da vergonha alheia.",
    "A bola te ignorou. E o R$1 também.",
    "Sua mira caiu mais que meu saldo no fim do mês.",
    "Esse erro foi tão grave que vai entrar na fatura do cartão.",
    "Doar dói menos que esse erro visual.",
    "Seu dedo tá com medo de me dar R$1? Prometo que uso bem.",
    "O universo conspirou. Contra o meu Pix.",
    "Só mais 57 erros e você desbloqueia o modo 'culpa'.",
    "Você está no top 1 de cliques que não rendem R$1.",
    "Se existisse cashback de erro, você estaria milionário.",
    "Errou com gosto. Só faltou o gosto de me ajudar com 1 real.",
    "Essa mira é tipo meta de ano novo: bonita só na teoria.",
    "Seu clique passou tão longe que nem a Anatel conseguiu rastrear.",
    "Cada erro é um elogio... ao meu azar.",
    "Sua aversão ao acerto tá quase poética.",
    "Você desbloqueou o troféu: 'Evasão de Pix'.",
    "Esse clique teve a mesma eficácia de mensagem de banco às 3h da manhã.",
    "A bola ficou tão tranquila que nem piscou.",
    "Parece que seu dedo tá em greve por direitos... de não doar.",
    "Com tanta tentativa errada, seu score de doação já tá negativado.",
    "Você treinou onde? No modo 'Ignorar a caridade'?",
    "A bola não tá se mexendo. Mas seu dedo, sim. Pra longe do meu R$1.",
    "A única coisa que você atingiu foi minha paciência.",
    "Se fosse pra evitar doar, você venceu com louvor.",
    "Esse clique foi mais inútil que 1 real em criptomoeda em 2022.",
    "PIX perdido na transação... emocional.",
    "Com esse desempenho, até a bola está cogitando te doar R$1 por dó.",
    "Você está a um erro de distância de eu desistir da esperança.",
    "Doação cancelada por ausência de talento.",
    "Essa bola tá parada há tanto tempo quanto meu saldo: esperando.",
    "Doar é simples. Acertar também deveria ser.",
    "Você não errou o alvo. Errou o propósito do jogo.",
    "Esse erro foi tão feio que o Banco Central quer regulamentar.",
    "Nem a febre do Pix te pegou, né?",
    "O mundo gira, a bola não. E você ainda erra.",
    "Clique com intenção, não com indecisão.",
    "Você treinou esse erro? Ficou perfeito!",
    "Até o botão de doar já desligou a esperança.",
    "Tente novamente... mas dessa vez, com vontade de ajudar.",
    "Já pensou em doar só pela vergonha desses erros?",
    "Nem o ChatGPT consegue prever se você um dia vai acertar.",
    "A bola nem piscou. Meu Pix também não.",
    "Seu dedo e o R$1 nunca se encontram... trágico.",
    "Errou, mas pelo menos agora está devendo moralmente.",
    "De novo? Essa bola já vai pedir música no Fantástico da fuga do R$1.",
    "Doar era fácil. Você complicou com estilo.",
    "Minha expectativa por R$1 caiu mais que esse clique.",
];